import { createElement } from '@lwc/engine-dom';
import ItemPurchaseApp from 'c/itemPurchaseApp';

describe('c-item-purchase-app', () => {
    afterEach(() => {

        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {

        const element = createElement('c-item-purchase-app', {
            is: ItemPurchaseApp
        });


        document.body.appendChild(element);


        expect(1).toBe(1);
    });
});